const state={map:null,submarketLayer:null,selected:null,features:[],labels:[],basemaps:{}};
const palette=['#3b82f6','#06b6d4','#10b981','#84cc16','#f59e0b','#f97316','#ef4444','#ec4899','#8b5cf6','#6366f1'];
function colorFor(id){const n=parseInt(id.replace('SM-',''),10);return palette[(n-1)%palette.length];}
function fmt(v,suffix=''){if(v===null||v===undefined||v==='')return 'TBD';return `${v}${suffix}`;}
function styleFeature(feature){const id=feature.properties.SubmarketID;const selected=state.selected&&state.selected.properties.SubmarketID===id;return{color:selected?'#111827':'#27364a',weight:selected?3:1.35,fillColor:colorFor(id),fillOpacity:selected?.55:.32};}
function initMap(){state.map=L.map('map',{zoomControl:false});L.control.zoom({position:'bottomright'}).addTo(state.map);state.basemaps.light=L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{attribution:'&copy; OpenStreetMap &copy; CARTO',maxZoom:20}).addTo(state.map);state.basemaps.streets=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors',maxZoom:19});state.basemaps.topo=L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenTopoMap contributors',maxZoom:17});L.control.scale({imperial:true,metric:true}).addTo(state.map);const legend=L.control({position:'bottomright'});legend.onAdd=()=>{const d=L.DomUtil.create('div','legend');d.innerHTML='<b>Enterprise Submarkets</b>Click a polygon to view details.';return d};legend.addTo(state.map);}
async function loadData(){const [geojson,meta]=await Promise.all([fetch('data/submarkets.geojson').then(r=>r.json()),fetch('data/metadata.json').then(r=>r.json())]);state.features=geojson.features;document.getElementById('releasePanel').innerHTML=`Version: <b>${meta.version}</b><br>Submarkets loaded: <b>${meta.uniqueSubmarketsLoaded}</b><br>Updated: <b>${meta.releaseDate}</b>`;document.getElementById('statusText').textContent=`${meta.uniqueSubmarketsLoaded} submarkets loaded`;state.submarketLayer=L.geoJSON(geojson,{style:styleFeature,onEachFeature:(feature,layer)=>{layer.on({mouseover:()=>layer.setStyle({weight:2.5,fillOpacity:.48}),mouseout:()=>state.submarketLayer.resetStyle(layer),click:()=>selectFeature(feature,layer)});const p=feature.properties;layer.bindTooltip(`${p.SubmarketID} | ${p.DisplayName}`,{sticky:true,className:'submarket-label'});}}).addTo(state.map);state.map.fitBounds(state.submarketLayer.getBounds(),{padding:[20,20]});}
function selectFeature(feature,layer){state.selected=feature;state.submarketLayer.setStyle(styleFeature);layer.setStyle(styleFeature(feature));state.map.fitBounds(layer.getBounds(),{padding:[40,40],maxZoom:10});renderSelected(feature.properties);}
function renderSelected(p){document.getElementById('selectedPanel').classList.remove('empty');document.getElementById('selectedPanel').innerHTML=`<h3 class="selected-title">${p.DisplayName}</h3><p class="selected-subtitle">${p.SubmarketID} • ${p.PolygonParts} polygon part${p.PolygonParts==1?'':'s'}</p><div class="metric-grid"><div class="metric"><div class="label">Area</div><div class="value">${fmt(p.AreaSqMi,' sq mi')}</div></div><div class="metric"><div class="label">Acres</div><div class="value">${fmt(p.Acres)}</div></div><div class="metric"><div class="label">Latitude</div><div class="value">${fmt(p.CentroidLat)}</div></div><div class="metric"><div class="label">Longitude</div><div class="value">${fmt(p.CentroidLon)}</div></div></div><div class="coming"><b>Coming next:</b> school intelligence, demographics, builder competition, and site evaluation scoring.</div>`;}
function search(){const q=document.getElementById('searchInput').value.trim().toLowerCase();if(!q)return;let foundLayer=null,foundFeature=null;state.submarketLayer.eachLayer(layer=>{const p=layer.feature.properties;if(p.SubmarketID.toLowerCase().includes(q)||p.DisplayName.toLowerCase().includes(q)){foundLayer=layer;foundFeature=layer.feature;}});if(foundLayer)selectFeature(foundFeature,foundLayer);else alert('No matching submarket found.');}
function bindUI(){document.getElementById('searchBtn').addEventListener('click',search);document.getElementById('searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')search();});document.getElementById('resetBtn').addEventListener('click',()=>{if(state.submarketLayer)state.map.fitBounds(state.submarketLayer.getBounds(),{padding:[20,20]});});document.getElementById('toggleSubmarkets').addEventListener('change',e=>{if(e.target.checked)state.submarketLayer.addTo(state.map);else state.map.removeLayer(state.submarketLayer);});document.getElementById('basemapSelect').addEventListener('change',e=>{Object.values(state.basemaps).forEach(l=>state.map.removeLayer(l));state.basemaps[e.target.value].addTo(state.map);state.basemaps[e.target.value].bringToBack();});}
initMap();bindUI();loadData().catch(err=>{console.error(err);document.getElementById('statusText').textContent='Error loading atlas data';});