function renderMarketSummary(p){ const s=scoreSummaryForSubmarket(p.SubmarketID); document.getElementById('selectedPanel').classList.remove('empty'); document.getElementById('selectedPanel').innerHTML=`
  <div class="selected-title">${p.DisplayName||p.SubmarketName}</div><div class="selected-subtitle">${p.Hub||''} • ${p.SubmarketID}</div>
  <div class="metric-grid"><div class="metric-card"><small>Area</small><b>${num(p.AreaSqMi,2)} sq mi</b></div><div class="metric-card"><small>Acres</small><b>${num(p.Acres,0)}</b></div><div class="metric-card"><small>School Rating</small><b>${fmtScore(s.overall)}</b></div><div class="metric-card"><small>Median Income</small><b>Pending</b></div></div>
  ${renderSchoolCard(s)}
`; renderStatusPanel(s); }
function renderSchoolCard(s){ const pending=s.overall==null; return `<div class="school-card"><div class="school-card-head"><h3>School Rating</h3><span class="rating-pill ${pending?'rating-pending':''}">${pending?'Pending':gradeFor(s.overall)}</span></div><div class="overall-score"><span>${fmtScore(s.overall)}</span><small>/10 Overall • ${s.count} rated schools</small></div><div class="score-grid"><div class="score-box"><small>Elementary</small><b>${fmtScore(s.elem)}</b></div><div class="score-box"><small>Middle</small><b>${fmtScore(s.middle)}</b></div><div class="score-box"><small>High</small><b>${fmtScore(s.high)}</b></div></div>${s.rows.length?`<details class="school-used"><summary>Schools used in calculation</summary>${s.rows.sort((a,b)=>a.SchoolName.localeCompare(b.SchoolName)).map(r=>`<div class="school-used-row"><span>${r.SchoolName}</span><b>${r.Rating}/10</b></div>`).join('')}</details>`:'<p class="helper-text">School ratings calculate from loaded school locations. Unrated schools are ignored.</p>'}</div>`; }
function renderStatusPanel(s){ document.getElementById('statusPanel').innerHTML=`<div><span>Boundaries</span><b>Verified</b></div><div><span>School Rating</span><b>${s.count?'Loaded':'Pending'}</b></div><div><span>Demographics</span><b>Pending</b></div><div><span>Builder Competition</span><b>Pending</b></div>`; }
function renderHubList(){ const hubs={}; GCSA.features.forEach(f=>{ const p=f.properties; hubs[p.Hub]=hubs[p.Hub]||{count:0,color:p.HubColor||p.HubBaseColor,features:[]}; hubs[p.Hub].count++; hubs[p.Hub].features.push(f); }); document.getElementById('hubList').innerHTML=Object.entries(hubs).map(([name,h])=>`<div class="hub-row" data-hub="${name}"><span class="hub-swatch" style="background:${h.color}"></span><span>${name}</span><b>${h.count}</b></div>`).join(''); document.querySelectorAll('.hub-row').forEach(el=>el.addEventListener('click',()=>{ const name=el.dataset.hub; const layers=[]; GCSA.submarketLayer.eachLayer(l=>{ if(l.feature.properties.Hub===name) layers.push(l);}); if(layers.length){ const group=L.featureGroup(layers); GCSA.map.fitBounds(group.getBounds(),{padding:[40,40]}); }})); }
function renderQuickSearch(){ const items=GCSA.features.slice(0,5); document.getElementById('quickSearch').innerHTML=items.map(f=>{const p=f.properties; return `<div class="quick-item" data-id="${p.SubmarketID}"><span class="quick-badge">SM</span><div><b>${p.DisplayName}</b><small>${p.Hub} • ${p.SubmarketID}</small></div></div>`}).join('')+`<p class="helper-text">Search more submarkets and schools. Additional city, builder, and retail search will be added as those layers load.</p>`; document.querySelectorAll('.quick-item').forEach(el=>el.addEventListener('click',()=>focusSubmarket(el.dataset.id))); }
function focusSubmarket(id){ const f=GCSA.features.find(x=>x.properties.SubmarketID===id); if(!f)return; const layer=f.properties._layer; if(layer){ GCSA.map.fitBounds(layer.getBounds(),{padding:[40,40]}); selectSubmarket(f.properties,layer); } }
