function schoolType(props){ const n=String(props.NAME||'').toLowerCase(); if(n.includes('elementary'))return 'Elementary'; if(n.includes('middle'))return 'Middle'; if(n.includes('high'))return 'High'; return 'Other'; }
function schoolIcon(type){ const cls=type==='Elementary'?'school-elementary':type==='Middle'?'school-middle':type==='High'?'school-high':'school-other'; const l=type==='Elementary'?'E':type==='Middle'?'M':type==='High'?'H':'S'; return L.divIcon({className:'',html:`<div class="school-marker ${cls}">${l}</div>`,iconSize:[22,22],iconAnchor:[11,11]}); }
function assignSchool(s){ const pt=s.geometry.coordinates; const match=GCSA.features.find(f=>pointInGeometry(pt,f.geometry)); const p=s.properties; if(match){ p.SubmarketID=match.properties.SubmarketID; p.SubmarketName=match.properties.DisplayName; p.Hub=match.properties.Hub; } else { p.SubmarketID=''; p.SubmarketName=''; p.Hub=''; } const r=ratingForSchoolName(p.NAME); if(r){ p.GreatSchoolsRating=r.Rating; p.RatingSourceName=r.SchoolName; } else p.GreatSchoolsRating=null; }
function schoolQueryBounds(){ const b=GCSA.submarketLayer.getBounds(); return `${b.getWest()},${b.getSouth()},${b.getEast()},${b.getNorth()}`; }
async function loadSchools(showLayer=false){
  if(GCSA.schoolsLoaded){ if(showLayer && GCSA.schoolLayer && !GCSA.map.hasLayer(GCSA.schoolLayer)) GCSA.schoolLayer.addTo(GCSA.map); return; }
  document.getElementById('schoolCountBadge').textContent='Loading...';
  const params=new URLSearchParams({f:'geojson',where:"STATE IN ('AL','FL')",outFields:GCSA_CONFIG.schoolOutFields,returnGeometry:'true',spatialRel:'esriSpatialRelIntersects',geometry:schoolQueryBounds(),geometryType:'esriGeometryEnvelope',inSR:'4326',outSR:'4326'});
  const data=await fetch(`${GCSA_CONFIG.ncesUrl}?${params.toString()}`).then(r=>r.json());
  GCSA.schools=(data.features||[]).filter(f=>f.geometry&&f.geometry.coordinates).map(f=>{ f.properties.SchoolType=schoolType(f.properties); assignSchool(f); return f; });
  GCSA.schoolLayer=L.geoJSON({type:'FeatureCollection',features:GCSA.schools},{ pointToLayer:(feature,latlng)=>L.marker(latlng,{icon:schoolIcon(feature.properties.SchoolType)}), onEachFeature:(feature,layer)=>{ const p=feature.properties; layer.bindPopup(`<div class="school-popup"><h3>${p.NAME}</h3><p><b>Type:</b> ${p.SchoolType}</p><p><b>GreatSchools:</b> ${p.GreatSchoolsRating? p.GreatSchoolsRating+'/10':'Not loaded'}</p><p><b>Location:</b> ${p.CITY}, ${p.STATE}</p><p><b>County:</b> ${p.NMCNTY||''}</p><p><b>Submarket:</b> ${p.SubmarketName||'Outside submarket boundary'}</p><p><b>NCES ID:</b> ${p.NCESSCH||''}</p></div>`); layer.on('click',()=>selectSchool(feature,false)); layer.on('dblclick',()=>selectSchool(feature,true)); }});
  GCSA.schoolsLoaded=true; document.getElementById('schoolCountBadge').textContent=`${GCSA.schools.length} loaded`; updateSearchIndex(); refreshSubmarketStyles(); if(showLayer) GCSA.schoolLayer.addTo(GCSA.map);
}
function selectSchool(s,zoom){ const coords=s.geometry.coordinates; if(zoom) GCSA.map.setView([coords[1],coords[0]],14); }
function setSchoolsVisible(on){ if(on){ GCSA.mapTheme='schools'; document.getElementById('mapThemeSelect').value='schools'; loadSchools(true); } else { if(GCSA.schoolLayer && GCSA.map.hasLayer(GCSA.schoolLayer)) GCSA.map.removeLayer(GCSA.schoolLayer); GCSA.mapTheme='hub'; document.getElementById('mapThemeSelect').value='hub'; refreshSubmarketStyles(); } }
function scoreSummaryForSubmarket(id){ if(!GCSA.schoolsLoaded) return {overall:null,elem:null,middle:null,high:null,count:0,rows:[]}; const rows=GCSA.schools.filter(s=>s.properties.SubmarketID===id && s.properties.GreatSchoolsRating).map(s=>({SchoolName:s.properties.NAME,SchoolType:s.properties.SchoolType,Rating:Number(s.properties.GreatSchoolsRating)})); const avg=a=>a.length? a.reduce((x,y)=>x+y,0)/a.length:null; return {overall:avg(rows.map(r=>r.Rating)), elem:avg(rows.filter(r=>r.SchoolType==='Elementary').map(r=>r.Rating)), middle:avg(rows.filter(r=>r.SchoolType==='Middle').map(r=>r.Rating)), high:avg(rows.filter(r=>r.SchoolType==='High').map(r=>r.Rating)), count:rows.length, rows}; }
function exportMissingRatings(){ loadSchools(false).then(()=>{ const rows=GCSA.schools.filter(s=>!s.properties.GreatSchoolsRating).map(s=>[s.properties.NMCNTY||'',s.properties.CITY||'',s.properties.NAME||'',s.properties.SchoolType||'','']); const csv='County,City,School Name,School Type,GreatSchools Rating (1-10)\n'+rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n'); downloadText('missing_greatschools_ratings.csv',csv); }); }
